spring: 
  port: 8080  
  mail: 
    host: smtp.gmail.com
    port: 567
    properties:
        mail:
            smtp:              
                auth: true
                starttls:
                    required: true
                    enable: true
                    
    username: 
    password: 
  datasource: 
    url: jdbc:mysql://localhost:3306/disneyAlkemy?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  thymeleaf:
    cache: false 
server:
    
  error:
    whitelabel:
      enabled: false
